openapi: "3.0.0"
info:
  version: 1.0.1
  title: Smartmate API
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /bookmarks:
    get:
      summary: List all user's bookmarks
      operationId: listBookmarks
      tags:
        - bookmarks
      parameters:
        - name: page
          in: query
          description: Number of requested page
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: per
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: A paged array of bookmarks
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/BookmarkPage"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
    post:
      summary: Create a bookmark
      operationId: createBookmark
      tags:
        - bookmarks
      requestBody:
        description: JSON with new Bookmark
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Bookmark"
      responses:
        '200':
          description: Bookmark successful created
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
  /bookmarks/{bookmarkId}:
    patch:
      summary: Update a specific bookmark
      operationId: updateBookmarkById
      tags:
        - bookmarks
      parameters:
        - name: bookmarkId
          in: path
          required: true
          description: The id of the bookmark to update
          schema:
            type: integer
      requestBody:
        description: JSON with updated Bookmark
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Bookmark"
      responses:
        '200':
          description: The Bookmark successful updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bookmark"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
  /tasks:
    get:
      summary: List all user's tasks
      operationId: listTasks
      tags:
        - tasks
      parameters:
        - name: page
          in: query
          description: Number of requested page
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: per
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: A paged array of tasks
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/TaskPage"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
    post:
      summary: Create a task
      operationId: createTask
      tags:
        - tasks
      requestBody:
        description: JSON with new Task
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
  /tasks/{taskId}:
    patch:
      summary: Update a specific task
      operationId: showTaskById
      tags:
        - tasks
      parameters:
        - name: taskId
          in: path
          required: true
          description: The id of the task to update
          schema:
            type: integer
      requestBody:
        description: JSON with updated Task
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        '200':
          description: The Task successful updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
components:
  schemas:
    Bookmark:
      type: object
      required:
        - name
        - link
        - imageUrl
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        link: 
          type: string
        imageUrl:
          type: string
        isFavorite:
          type: boolean
        dateCreate:
          type: string
          format: date-time
        tag:
          type: string
    Bookmarks:
      type: array
      items:
        $ref: "#/components/schemas/Bookmark"
    Task:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        description:
          type: string
        isResolved:
          type: boolean
          default: false
        dateCreate: 
          type: string
          format: date-time
        dateCompetion: 
          type: string
          format: date-time
        tag:
          type: string
    Tasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"
    BookmarkPage:
      type: object
      required: 
        - data
        - page
      properties:
        data:
          $ref: "#/components/schemas/Bookmarks"
        page:
          $ref: "#/components/schemas/Page"
    TaskPage:
      type: object
      required: 
        - data
        - page
      properties:
        data:
          $ref: "#/components/schemas/Tasks"
        page:
          $ref: "#/components/schemas/Page"
    APIError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Page:
      type: object
      required:
        - position
        - data
      properties:
        position:
          type: object
          required:
            - current
            - max
          properties:
            current: 
              type: integer
              format: int32
            max:
              type: integer
              format: int32
        data:
          type: object
          required:
            - per
            - total
          properties:
            per:
              type: integer
              format: int32
            total:
              type: integer
              format: int32
