//
// APIError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct APIError: Codable {

    public var code: Int
    public var message: String

    public init(code: Int, message: String) {
        self.code = code
        self.message = message
    }


}

