//
// BookmarkPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct BookmarkPage: Codable {

    public var data: [Bookmark]
    public var page: Page

    public init(data: [Bookmark], page: Page) {
        self.data = data
        self.page = page
    }


}

