//
// PageData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PageData: Codable {

    public var per: Int
    public var total: Int

    public init(per: Int, total: Int) {
        self.per = per
        self.total = total
    }


}

