//
// Page.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Page: Codable {

    public var position: PagePosition
    public var data: PageData

    public init(position: PagePosition, data: PageData) {
        self.position = position
        self.data = data
    }


}

