//
// PagePosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PagePosition: Codable {

    public var current: Int
    public var max: Int

    public init(current: Int, max: Int) {
        self.current = current
        self.max = max
    }


}

