//
// TaskPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TaskPage: Codable {

    public var data: [Task]
    public var page: Page

    public init(data: [Task], page: Page) {
        self.data = data
        self.page = page
    }


}

