//
// Task.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Task: Codable, Identifiable {

    public var id: Int64?
    public var name: String
    public var description: String?
    public var isResolved: Bool = false
    public var dateCreate: Date?
    public var dateCompetion: Date?
    public var tag: String?

    public init(id: Int64? = nil, name: String, description: String?, isResolved: Bool, dateCreate: Date?, dateCompetion: Date?, tag: String?) {
        self.id = id
        self.name = name
        self.description = description
        self.isResolved = isResolved
        self.dateCreate = dateCreate
        self.dateCompetion = dateCompetion
        self.tag = tag
    }


}

